package models;
// Generated 09-feb-2017 13:27:33 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Barco generated by hbm2java
 */
public class Barco implements java.io.Serializable {

	private Integer idBarco;
	private String nombre;
	private String size;
	private String tipo;
	private double tonelaje;
	private Set inventarios = new HashSet(0);
	private Set estancias = new HashSet(0);

	public Barco() {
	}

	public Barco(String nombre, String size, String tipo, double tonelaje) {
		this.nombre = nombre;
		this.size = size;
		this.tipo = tipo;
		this.tonelaje = tonelaje;
	}

	public Barco(String nombre, String size, String tipo, double tonelaje, Set inventarios, Set estancias) {
		this.nombre = nombre;
		this.size = size;
		this.tipo = tipo;
		this.tonelaje = tonelaje;
		this.inventarios = inventarios;
		this.estancias = estancias;
	}

	public Integer getIdBarco() {
		return this.idBarco;
	}

	public void setIdBarco(Integer idBarco) {
		this.idBarco = idBarco;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public double getTonelaje() {
		return this.tonelaje;
	}

	public void setTonelaje(double tonelaje) {
		this.tonelaje = tonelaje;
	}

	public Set getInventarios() {
		return this.inventarios;
	}

	public void setInventarios(Set inventarios) {
		this.inventarios = inventarios;
	}

	public Set getEstancias() {
		return this.estancias;
	}

	public void setEstancias(Set estancias) {
		this.estancias = estancias;
	}

}
