package models;
// Generated 09-feb-2017 13:27:33 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Mercancia generated by hbm2java
 */
public class Mercancia implements java.io.Serializable {

	private int idMercancia;
	private String nombre;
	private double peso;
	private Set inventarios = new HashSet(0);

	public Mercancia() {
	}

	public Mercancia(int idMercancia, String nombre, double peso) {
		this.idMercancia = idMercancia;
		this.nombre = nombre;
		this.peso = peso;
	}

	public Mercancia(int idMercancia, String nombre, double peso, Set inventarios) {
		this.idMercancia = idMercancia;
		this.nombre = nombre;
		this.peso = peso;
		this.inventarios = inventarios;
	}

	public int getIdMercancia() {
		return this.idMercancia;
	}

	public void setIdMercancia(int idMercancia) {
		this.idMercancia = idMercancia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public double getPeso() {
		return this.peso;
	}

	public void setPeso(double peso) {
		this.peso = peso;
	}

	public Set getInventarios() {
		return this.inventarios;
	}

	public void setInventarios(Set inventarios) {
		this.inventarios = inventarios;
	}

}
