package models;
// Generated 09-feb-2017 13:27:33 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Muelle generated by hbm2java
 */
public class Muelle implements java.io.Serializable {

	private Integer idMuelle;
	private String size;
	private Boolean ocupado;
	private Set estancias = new HashSet(0);

	public Muelle() {
	}

	public Muelle(String size) {
		this.size = size;
	}

	public Muelle(String size, Boolean ocupado, Set estancias) {
		this.size = size;
		this.ocupado = ocupado;
		this.estancias = estancias;
	}

	public Integer getIdMuelle() {
		return this.idMuelle;
	}

	public void setIdMuelle(Integer idMuelle) {
		this.idMuelle = idMuelle;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public Boolean getOcupado() {
		return this.ocupado;
	}

	public void setOcupado(Boolean ocupado) {
		this.ocupado = ocupado;
	}

	public Set getEstancias() {
		return this.estancias;
	}

	public void setEstancias(Set estancias) {
		this.estancias = estancias;
	}

}
